# Generated by Django 4.2.5 on 2023-09-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='user',
        ),
    ]
